from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import spearmanr


BASE = Path(__file__).resolve().parents[1]
IN_PQ = BASE / "data" / "fig_table_gen" / "retro_interp_forecast_varyear.parquet"
OUT_DIR = BASE / "output"

MODES = [
    ("retrodiction",  "A. Backcasting",   "#8B1A1A"),
    ("interpolation", "B. Interpolation", "#B86800"),
    ("forecast",      "C. Forecasting",   "#1A5F1A"),
]


def panel(ax: plt.Axes, d: pd.DataFrame, title: str, color: str) -> None:
    pred = d["GLM_predicted"].to_numpy(dtype=np.float64)
    obs  = d["obs_wavg"].to_numpy(dtype=np.float64)
    diff = pred - obs
    if len(pred) < 3:
        ax.text(0.5, 0.5, f"n={len(pred)}", transform=ax.transAxes,
                ha="center", va="center")
        ax.set_title(title, loc="left", fontsize=22)
        return

    sp_val, _ = spearmanr(pred, obs)
    mae  = float(np.abs(diff).mean())

    diff_abs = np.abs(diff)
    for lo, hi, alpha in [(0.00, 0.03, 0.8), (0.03, 0.05, 0.4),
                          (0.05, np.inf, 0.2)]:
        mask = (diff_abs >= lo) & (diff_abs < hi)
        if mask.any():
            ax.scatter(pred[mask], obs[mask], s=3, c=color,
                       alpha=alpha, edgecolors="none")

    bbox_kw = dict(facecolor="none", edgecolor="none", pad=0)
    ax.text(0.02, 0.95, f"Spearman $\\rho$ = {sp_val:.2f}",
            transform=ax.transAxes, ha="left", va="top", fontsize=18,
            bbox=bbox_kw)
    ax.text(0.02, 0.88, f"MAE = {mae:.3f}",
            transform=ax.transAxes, ha="left", va="top", fontsize=18,
            bbox=bbox_kw)

    ax.set_xlabel("Predicted Mean Responses")
    ax.set_ylabel("Observed Mean Responses")
    ax.set_title(title, loc="left", fontsize=22)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)


def main() -> None:
    OUT_DIR.mkdir(exist_ok=True)
    df = pd.read_parquet(IN_PQ)
    df = df.dropna(subset=["GLM_predicted", "obs_wavg", "mode"])
    # One row per (variable, year) — average across folds for a clean aggregate.
    df = (df.groupby(["variable", "year", "mode"], as_index=False)
            [["GLM_predicted", "obs_wavg"]].mean())

    plt.rcParams.update({
        "font.family": "DejaVu Sans",
        "font.size": 18,
        "axes.titlesize": 22,
        "axes.labelsize": 20,
        "xtick.labelsize": 16,
        "ytick.labelsize": 16,
        "legend.fontsize": 16,
        "figure.titlesize": 22,
        "axes.spines.top": True,
        "axes.spines.right": True,
        "axes.grid": True,
        "axes.axisbelow": True,
        "grid.color": "0.92",
        "grid.linewidth": 0.5,
    })

    fig, axes = plt.subplots(1, 3, figsize=(13, 4.5))
    for ax, (mode, title, color) in zip(axes, MODES):
        panel(ax, df.loc[df["mode"] == mode], title, color)
        ax.set_aspect("equal", adjustable="box")

    fig.tight_layout(w_pad=1.0)

    out_pdf = OUT_DIR / "figure_retro_interp_forecast.pdf"
    out_png = OUT_DIR / "figure_retro_interp_forecast.png"
    fig.savefig(out_pdf)
    fig.savefig(out_png, dpi=300)
    print(f"saved: {out_pdf}")
    print(f"saved: {out_png}")

    # Caption / metadata .tex — LaTeX-includable
    counts = {m: int((df["mode"] == m).sum()) for m, _, _ in MODES}
    n_retro = f"{counts['retrodiction']:,}"
    n_interp = f"{counts['interpolation']:,}"
    n_fore = f"{counts['forecast']:,}"
    caption_body = (
        r"\caption{Year-level prediction accuracy by temporal regime within "
        r"the umbrella retrodiction task. "
        r"Each panel shows GSS-observed proportions ($y$-axis) vs.\ "
        r"GLM-calibrated Alpaca predictions ($x$-axis) aggregated at the "
        r"(variable, year) level over 10-fold partial CV. "
        r"Variable-level classification: for a validation $(v, y)$, let "
        r"$O_v \setminus \{y\}$ be the variable's other observation years; "
        r"$y < \min$ = backcasting, $y > \max$ = forecasting, otherwise "
        r"interpolation. "
        "Backcasting $N = " + n_retro + "$; "
        "Interpolation $N = " + n_interp + "$; "
        "Forecasting $N = " + n_fore + "$.}"
    )
    cap_tex = OUT_DIR / "figure_retro_interp_forecast_caption.tex"
    cap_tex.write_text(
        "% Auto-generated by 4_figures-tables/figure_retro_interp_forecast.py\n"
        "% Sample sizes (variable-year aggregates, averaged across folds):\n"
        f"%   Backcasting   : N = {n_retro}\n"
        f"%   Interpolation : N = {n_interp}\n"
        f"%   Forecasting   : N = {n_fore}\n\n"
        + caption_body + "\n"
    )
    print(f"saved: {cap_tex}")


if __name__ == "__main__":
    main()
