from pathlib import Path

import pandas as pd


BASE = Path(__file__).resolve().parents[1]
IN_PATH = BASE / "data" / "fig_table_gen" / "alpaca_examples.parquet"
OUT_TEX = BASE / "output" / "table_alpaca_text_examples.tex"

TARGET_VARS = ["homosex", "marhomo1", "busing", "nomeat"]

NOTE = (
    "Note: These responses were generated without reflecting a particular "
    "individual's opinions in our training data. These responses were "
    "generated solely to check whether the model understands the semantic "
    "meaning of survey questions correctly."
)


def _tex_escape(s: str) -> str:
    if not isinstance(s, str):
        return ""
    return (s.replace("\\", r"\textbackslash{}")
             .replace("&", r"\&").replace("%", r"\%").replace("$", r"\$")
             .replace("#", r"\#").replace("_", r"\_").replace("{", r"\{")
             .replace("}", r"\}").replace("~", r"\textasciitilde{}")
             .replace("^", r"\textasciicircum{}"))


def main():
    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    df = pd.read_parquet(IN_PATH)
    df = (df.set_index("variable").loc[
            [v for v in TARGET_VARS if v in df["variable"].values]]
            .reset_index())

    rows = "\n".join(
        f"{_tex_escape(r['variable'])} & {_tex_escape(r['question'])} "
        f"& {_tex_escape(r['response'])} \\\\"
        for _, r in df.iterrows()
    )

    tex = r"""\begin{table}[!h]
    \label{table:tables1}
    \caption{\textbf{Examples of text responses generated by the Alpaca-7b model.} }
    \renewcommand{\arraystretch}{1.5}
    \begin{center}
        \begin{tabular}{p{0.15\textwidth} p{0.375\textwidth} p{0.375\textwidth}}
            \toprule
            \textbf{Variables} & \textbf{Survey questions} & \textbf{Text responses} \\
            \midrule
""" + rows + r"""
           \bottomrule
        \end{tabular}
\end{center}
\end{table}

\noindent """ + NOTE + "\n"

    OUT_TEX.write_text(tex)
    print(f"Saved: {OUT_TEX} ({len(df)} rows)")


if __name__ == "__main__":
    main()
